// packages/vue/src/ui/ColorPickerPanel.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue'

defineProps<{
  compact?: boolean
  hideContrastRatio?: boolean
  hideDefaultSwatches?: boolean
}>()

const model = defineModel<string>({ default: '#000000' })

const hexDraft = ref(model.value)

watch(model, (value) => {
  hexDraft.value = value
})

const isValidHex = computed(() => /^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/.test(hexDraft.value))

function commitHex(): void {
  if (isValidHex.value) model.value = hexDraft.value
}

function onNativeColorInput(event: Event): void {
  const value = (event.target as HTMLInputElement).value
  hexDraft.value = value
  model.value = value
}
</script>

<template>
  <div class="xpe-color-picker">
    <input
      type="color"
      class="xpe-color-swatch"
      :value="model"
      @input="onNativeColorInput"
    />
    <input
      v-model="hexDraft"
      type="text"
      class="xpe-color-hex"
      spellcheck="false"
      placeholder="#000000"
      @keydown.enter.prevent="commitHex"
      @blur="commitHex"
    />
  </div>
</template>

<style scoped>
.xpe-color-picker {
  display: flex;
  align-items: center;
  gap: 8px;
}
.xpe-color-swatch {
  width: 32px;
  height: 32px;
  padding: 0;
  border: 1px solid #e5e7eb;
  border-radius: 8px;
  cursor: pointer;
  background: none;
}
.xpe-color-hex {
  flex: 1;
  height: 32px;
  border: 1px solid #e5e7eb;
  border-radius: 8px;
  padding: 0 8px;
  font-size: 12px;
  font-family: var(--xpe-font-mono, ui-monospace, monospace);
  outline: none;
}
.xpe-color-hex:focus {
  border-color: #6366f1;
}
</style>

// packages/react/src/ui/ColorPickerPanel.tsx
import { useEffect, useState } from 'react'

export function ColorPickerPanel({
  value,
  onChange,
}: {
  value: string
  onChange: (value: string) => void
  compact?: boolean
  hideContrastRatio?: boolean
  hideDefaultSwatches?: boolean
}) {
  const [hexDraft, setHexDraft] = useState(value)

  useEffect(() => {
    setHexDraft(value)
  }, [value])

  const isValidHex = /^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/.test(hexDraft)

  function commitHex() {
    if (isValidHex) onChange(hexDraft)
  }

  return (
    <div className="xpe-color-picker">
      <input
        type="color"
        className="xpe-color-swatch"
        value={value}
        onChange={(e) => {
          setHexDraft(e.target.value)
          onChange(e.target.value)
        }}
      />
      <input
        type="text"
        className="xpe-color-hex"
        spellCheck={false}
        placeholder="#000000"
        value={hexDraft}
        onChange={(e) => setHexDraft(e.target.value)}
        onKeyDown={(e) => {
          if (e.key === 'Enter') {
            e.preventDefault()
            commitHex()
          }
        }}
        onBlur={commitHex}
      />
    </div>
  )
}
